### ISSUE TITLE
request for advice on making databases active

### ISSUE THREAD

**Issue by pwin** [zazuko/fuseki-geosparql#3]
I'm connecting with HTTP to set up a store, I POST an assembler, and there is a new folder/DB set up (I looked inside the docker instance) but this new store is not reported with a /$/datasets call, and I cannot activate it as expected with HTTP - I've done a POST of {URL}/$/datasets/{DB_NAME}?state=active but it isn't seeming to be activated. ( https://jena.apache.org/documentation/fuseki2/fuseki-server-protocol.html )
Advice appreciated please

**Comment by ludovicm67** [comment]
Thank you @pwin for opening this issue in this repository.

Here are some information that will certainly help you and others that will go on this issue to understand this issue.

### Start a Fuseki instance

Start Fuseki with GeoSPARQL support using the following command:

```sh
docker run --rm -p3030:3030 -it ghcr.io/zazuko/fuseki-geosparql:v2.0.1
```

This will expose Fuseki to the 3030 port.

### Note about permissions

Administrations tasks requires credentials as specified in the `README.md` file.
Default credentials are: `admin` / `admin`.

You can use the `-u` option of `curl` to send credentials.

If you try to perform restricted requests without sending the right credentials, you will get something like this:

```sh
> curl -v http://localhost:3030/$/datasets

*   Trying ::1:3030...
* Connected to localhost (::1) port 3030 (#0)
> GET /$/datasets HTTP/1.1
> Host: localhost:3030
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Wed, 16 Feb 2022 21:00:36 GMT
< WWW-Authenticate: BASIC realm="application"
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

Note the `401 Unauthorized` in the response headers.

I'm using the `-v` option from `curl` to inspect the response headers, because without it you will only see an empty response.

### Fetch datasets

By default, the Docker image creates a dataset named `ds`.

So if we run the previous request by adding credentials, we should get this:

```sh
> curl -u admin:admin 'http://localhost:3030/$/datasets'

{
  "datasets" : [
      {
        "ds.name" : "/ds" ,
        "ds.state" : true ,
        "ds.services" : [
            {
              "srv.type" : "gsp-r" ,
              "srv.description" : "Graph Store Protocol (Read)" ,
              "srv.endpoints" : [
                  "get" ,
                  ""
                ]
            } ,
            {
              "srv.type" : "query" ,
              "srv.description" : "SPARQL Query" ,
              "srv.endpoints" : [
                  "query" ,
                  "sparql" ,
                  ""
                ]
            }
          ]
      }
    ]
}
```

### Create a new dataset

#### Using the web interface

You can create a new dataset directly from the UI: http://localhost:3030/#/manage/new
But this will not be GeoSPARQL datasets.

#### Using a simple POST request

If you create the dataset using the following command, you will also have the same issue:

```sh
curl -u admin:admin 'http://localhost:3030/$/datasets' \
  -X POST \
  --data-raw 'dbName=test&dbType=tdb2'
```

the dataset will be created, but it will not support GeoSPARQL.

It's basically the same request that is triggered using the web UI.

#### Using an assembly file

You may want to create it using an assembly file, like this:

```sh
# create a .ttl file with some configuration
cat << 'EOF' > /tmp/dataset.ttl
@prefix :        <#> .
@prefix fuseki:  <http://jena.apache.org/fuseki#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ja:      <http://jena.hpl.hp.com/2005/11/Assembler#> .
@prefix tdb2:      <http://jena.apache.org/2016/tdb#>
@prefix geosparql: <http://jena.apache.org/geosparql#>

<#geoService> rdf:type fuseki:Service;
  fuseki:name "geo";

  fuseki:endpoint [ fuseki:operation fuseki:query ; ];
  fuseki:endpoint [ fuseki:operation fuseki:query ; fuseki:name "sparql" ];
  fuseki:endpoint [ fuseki:operation fuseki:query ; fuseki:name "query" ];
  fuseki:endpoint [ fuseki:operation fuseki:gsp-r ; ];
  fuseki:endpoint [ fuseki:operation fuseki:gsp-r ; fuseki:name "get" ];

  fuseki:dataset <#geo> .

<#geo> rdf:type geosparql:geosparqlDataset ;
  geosparql:spatialIndexFile "databases/geo/spatial.index";

  # some GeoSPARQL settings
  geosparql:inference            true ;
  geosparql:queryRewrite         true ;
  geosparql:indexEnabled         true ;
  geosparql:applyDefaultGeometry false ;

  # 3 item lists: [Geometry Literal, Geometry Transform, Query Rewrite]
  geosparql:indexSizes           "-1,-1,-1" ;       # Default - unlimited.
  geosparql:indexExpires         "5000,5000,5000" ; # Default - time in milliseconds.

  geosparql:dataset <#geoDataset> ;
  .

<#geoDataset> rdf:type tdb2:DatasetTDB2 ;
  tdb2:location "databases/geo" ;
  tdb2:unionDefaultGraph true ;
  .
EOF

# do the request to create the dataset
curl -u admin:admin 'http://localhost:3030/$/datasets' \
  -X POST \
  -H "Accept: text/turtle" \
  -H "Content-Type: text/turtle" \
  --data @/tmp/dataset.ttl

# remove the temporary file we created
rm /tmp/dataset.ttl
```

But you will get the following error:

> Required base dataset missing: http://localhost:3030/$/datasets#geo

This is due because the Fuseki HTTP Administration Protocol does not support GeoSPARQL features in the current version (Apache Jena 4.4.0).

But for non-GeoSPARQL datasets, it is working as expected:

```sh
# create a .ttl file with some configuration
cat << 'EOF' > /tmp/dataset.ttl
@prefix :        <#> .
@prefix fuseki:  <http://jena.apache.org/fuseki#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ja:      <http://jena.hpl.hp.com/2005/11/Assembler#> .
@prefix tdb2:      <http://jena.apache.org/2016/tdb#>

<#classicalService> rdf:type fuseki:Service;
  fuseki:name "classical";

  fuseki:endpoint [ fuseki:operation fuseki:query ; ];
  fuseki:endpoint [ fuseki:operation fuseki:query ; fuseki:name "sparql" ];
  fuseki:endpoint [ fuseki:operation fuseki:query ; fuseki:name "query" ];
  fuseki:endpoint [ fuseki:operation fuseki:gsp-r ; ];
  fuseki:endpoint [ fuseki:operation fuseki:gsp-r ; fuseki:name "get" ];

  fuseki:dataset <#classicalDataset> .

<#classicalDataset> rdf:type tdb2:DatasetTDB2 ;
  tdb2:location "databases/classical" ;
  tdb2:unionDefaultGraph true ;
  .
EOF

# do the request to create the dataset
curl -u admin:admin 'http://localhost:3030/$/datasets' \
  -X POST \
  -H "Accept: text/turtle" \
  -H "Content-Type: text/turtle" \
  --data @/tmp/dataset.ttl

# remove the temporary file we created
rm /tmp/dataset.ttl
```

So it's definitely an upstream bug, maybe related to [JENA-2267](https://issues.apache.org/jira/browse/JENA-2267).

### Delete a dataset

To delete the datasets (`test` and `classical`) we created, you can run the following commands:

```sh
curl -u admin:admin -X DELETE 'http://localhost:3030/$/datasets/test'
curl -u admin:admin -X DELETE 'http://localhost:3030/$/datasets/classical'
```

### Changing the state of a dataset

You can take a dataset (let's say our default `ds` dataset) offline using this command:

```sh
curl -u admin:admin -X POST 'http://localhost:3030/$/datasets/ds?state=online'
```

And take it back online using the following command:

```sh
curl -u admin:admin -X POST 'http://localhost:3030/$/datasets/ds?state=active'
```

### Conclusions

I hope that this detailled answer is providing some useful information.

GeoSPARQL support is something new on Fuseki, and the support for the GeoSPARQL assembler for the initial configuration (our `config.ttl` file) only came in the 4.4.0 release of Apache Jena, which is the current version.
But it seems that the Fuseki HTTP Administration Protocol does not currently support it, we should wait until it gets supported in the Apache Jena project.

So currently the only way to create datasets with GeoSPARQL support would be to edit the `config.ttl` file, and restart the Fuseki instance.

Since it's running in a Docker container, you can easilly mount a custom `config.ttl` file at `/fuseki/config.ttl`.

**Comment by pwin** [comment]
Thanks @ludovicm67  that is really comprehensive, and very useful.  It should be in a wiki page -

**Comment by pwin** [comment]
I'm not seeing any management screen on port 3030 in the browser.  I'm also not seeing a list of the datasets I've created

**Comment by ludovicm67** [comment]
For the "wiki page" part, I will write some documentation somewhere when the issue in Apache Jena about the Fuseki HTTP Administration Protocol would be solved.

---

If you run the following command:

```sh
docker run --rm -p3030:3030 -it ghcr.io/zazuko/fuseki-geosparql:v2.0.1
```

Are you able to get the web interface at http://localhost:3030/#/?

If not, please make sure that:
- the port 3030 is available
- you are using the right Docker context

And if the web interface is still not available, can you paste some relevant logs here, so that I can help you?

**Comment by pwin** [comment]
curiously it appears on Edge, but on Chrome gives the following  ```GET http://localhost:3030/static/js/app.f0c68463.js 404 (Not Found)
localhost/:1          GET http://localhost:3030/static/js/datasetEdit.91dc754c.js net::ERR_ABORTED 404 (Not Found)
localhost/:1          GET http://localhost:3030/static/js/datasetInfo.85859a43.js net::ERR_ABORTED 404 (Not Found)
localhost/:1          GET http://localhost:3030/static/js/datasetQuery.3af92d0a.js net::ERR_ABORTED 404 (Not Found)
localhost/:1          GET http://localhost:3030/static/js/datasetUpload.7936769c.js net::ERR_ABORTED 404 (Not Found)
localhost/:1          GET http://localhost:3030/static/js/documentation.fd0da50e.js net::ERR_ABORTED 404 (Not Found)
localhost/:1          GET http://localhost:3030/static/js/manageDatasets.b25b7a1c.js net::ERR_ABORTED 404 (Not Found)
localhost/:1          GET http://localhost:3030/static/js/newDataset.24a21ac0.js net::ERR_ABORTED 404 (Not Found)
localhost/:1          GET http://localhost:3030/static/js/tasks.eca207a9.js net::ERR_ABORTED 404 (Not Found)

**Comment by ludovicm67** [comment]
It's definitively a caching issue.
Can you try to clear the cache of your Chrome browser?

**Comment by pwin** [comment]
VM52:6772 crbug/1173575, non-JS module files deprecated.

**Comment by ludovicm67** [comment]
Did you clear the cache of your browser? Are you using the latest version of Chrome?

**Comment by pwin** [comment]
yes I did, and afaik I am (Version 98.0.4758.82 (Official Build) (64-bit)).  Also, I've never had any issues before with the Fuseki web front end.

**Comment by ludovicm67** [comment]
Can you try the following: open a private browsing session on Chrome, and go to this page: http://localhost:3030/
JavaScript should be enabled.
What can you see in your browser?

For information, Apache Jena 4.4.0 released a new version for the web UI, it's now based on VueJS.

**Comment by pwin** [comment]
(index):6772 crbug/1173575, non-JS module files deprecated.

**Comment by pwin** [comment]
it worked in a private window.
